### ISSUE TITLE
development installation npm install error

### ISSUE THREAD

**Issue by jfunky** [processing/p5.accessibility#145]
- [x ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version: Google Chrome | 73.0.3683.86 (Official Build) (64-bit)
- Operating System: MacOSX Mojave Version 10.14.3 
- Steps to reproduce this:

Hello! When trying to follow the development instructions. I get errors running npm install. 

<img width="1265" alt="Screen Shot 2019-04-10 at 9 15 50 PM" src="https://user-images.githubusercontent.com/6812614/55924568-61992200-5bd8-11e9-9a68-2599c2b258c3.png">

I got as far as finding that I can run it if I remove all references to cryptiles from package-lock.json, but I'm not sure what to do next.

**Comment by jfunky** [comment]
@montoyamoraga

**Comment by lm-n** [comment]
Hi @jfunky, I just went through the installation and it seems to work for me. What npm version are you using? To ensure that your npm is up-to-date run `npm update -g npm` (this might require sudo on certain systems).

**Comment by jfunky** [comment]
Just tried again and it magically works now even before updating npm (at the time I tried updating, and also re-installed npm). Thanks for your help!
