### ISSUE TITLE
when noLoop() is called, content in draw() is not parsed

### ISSUE THREAD

**Issue by MathuraMG** [processing/p5.accessibility#21]
Content in draw is parsed only every 20 loops. Therefore loop = 1 is missed.
So if noLoop is called, the content is missed.
@lm-n

**Comment by MathuraMG** [comment]
updates on this -
Reason for the issue. Every 20th frame (after frame 0), the interceptor takes a tally of all objects present inside the draw loop, and in the NEXT frame, it populates the DOM elements with this content.
What is happening here is that the tally happens in frame 0 and population in frame 1. Thus it never tallies in frame 1 and the draw loop doesn't run after.

**Comment by lm-n** [comment]
I think this is what is giving us the problem with the editor @MathuraMG
