### ISSUE TITLE
Area for arc currently shows 0

### ISSUE THREAD

**Issue by MathuraMG** [processing/p5.accessibility#33]

**Comment by mithru** [comment]
Fixing this. Also realized that it might make sense to also describe the type of arc? Thoughts? (of course that can't be implemented under this area method) 

[p5 reference](https://p5js.org/reference/#/p5/arc) says this:

> If a mode parameter is provided, the arc will be filled like an open semi-circle (OPEN) , a closed semi-circle (CHORD), or as a closed pie segment (PIE).

**Comment by mithru** [comment]
@MathuraMG I believe this is resolved. If you agree, can you close the issue?

**Comment by MathuraMG** [comment]
fixed in #47
