### ISSUE TITLE
Include support for polygon

### ISSUE THREAD

**Issue by MathuraMG** [processing/p5.accessibility#34]

**Comment by mithru** [comment]
Same as #37 - it's not included in the main p5 reference page, but there's [an example here](https://p5js.org/examples/form-regular-polygon.html). 

Can PR to add to reference page if needed.

**Comment by mithru** [comment]
wait. just checked the example. polygon() is not part of the p5 lib. same with #37

**Comment by mithru** [comment]
@MathuraMG @lm-n  Should we close this and #37  ? They aren't primitive shapes but user-defined methods as seen in the example linked above.

**Comment by MathuraMG** [comment]
yes!
