### ISSUE TITLE
Include support for Star

### ISSUE THREAD

**Issue by MathuraMG** [processing/p5.accessibility#37]

**Comment by mithru** [comment]
No reference available in the main [p5 reference page](https://p5js.org/reference/)

I had no idea it existed until you told me! So cool! do you know if there's any reason it's not in the reference? Should I add make a PR to add it?

[I see this in the examples though](https://p5js.org/examples/form-star.html)

**Comment by lm-n** [comment]
@mithru yes if you can make a PR that would be great! that does happen with p5js.org some things are in the examples but not in the reference. You might also want to talk to Liz about it since she's working on the reference of primitive shapes

**Comment by mithru** [comment]
Just saw the example code for star() and #34 . doesn't seem like it's a primitive shape. The example has a method to generate star() and polygon(). 

Unless im missing something?
