### ISSUE TITLE
Change the name of the library to p5.accessibilty

### ISSUE THREAD

**Issue by MathuraMG** [processing/p5.accessibility#50]

**Comment by spiray** [comment]
@MathuraMG Can you clarify what needs to be done here?

**Comment by MathuraMG** [comment]
The name of [this](https://github.com/processing/p5.accessibility/blob/master/dist/p5-accessibility.js) file needs to be changed to p5.accessibility and we need to change the linrary link in places it is currently being used. Such as the p5 web editor and examples.

**Comment by spiray** [comment]
Understood, thanks
