### ISSUE TITLE
Sketch output don't go well on example pages

### ISSUE THREAD

**Issue by MayayTW1620** [processing/p5.accessibility#55]
When using the accessible library on example pages with the screen reader, list in text output will loop several times before actually read elements of the list.

And table output would not be read completely, after reading out the first line, the focus will jump to the icon of the webpage and go all over again. 

Not sure if it is a bug or something else.

**Comment by lm-n** [comment]
@MayayTW1620 please include the code that you were using so that we can try to replicate the issue

**Comment by MayayTW1620** [comment]
This problem is a normal problem when I tried VoiceOver on an example page with accessible library installed. Like this one [https://p5js.org/examples/structure-coordinates.html](url). When going with text output, the list will loop several times before reading elements of the list. I didn't change any code in except for 

`<section id="textOutput-content"></section>
    <section id="tableOutput-content"></section>
    <script src="https://cdn.rawgit.com/processing/p5.accessibility/v0.1.1/dist/p5-accessibility.js"></script>
`
in the body and 

`#textOutput-content, #tableOutput-content{
        position: static !important;
        left: 10px !important;
        top: auto !important;
        width: auto !important;
        height: auto !important;
        overflow: visible !important;
      }`

in the style section.

**Comment by MathuraMG** [comment]
was a local issue.
