### ISSUE TITLE
eslint doesn't load on grunt build for local reference

### ISSUE THREAD

**Issue by git-ebetts** [processing/p5.accessibility#58]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by git-ebetts** [comment]
Command line prompt 'npm run grunt' for local reference build produces one error: "Warning: Task "eslint:source" failed. Use --force to continue."

**Comment by spiray** [comment]
@git-ebetts the docs and commands have been updated. You can try again with `npm run build`. Let me know if you still have issues.
