### ISSUE TITLE
ensure all outputs in text and table round to two decimal places

### ISSUE THREAD

**Issue by mithru** [processing/p5.accessibility#59]
#### Nature of issue?

- [ ] Existing feature enhancement

#### Feature enhancement details:
Currently the text and table outputs display coordinates like 100/3 as 33.33333333333333. Let's round this down to 33.33. If it's coordinates, does the decimal even matter though? Thoughts?

**Comment by lm-n** [comment]
I don't think the decimal matters. What I did for color #52  was to round and get rid of decimals.

**Comment by MathuraMG** [comment]
Yea, let's get rid of the decimals!

**Comment by MathuraMG** [comment]
Round to NO decimal places

**Comment by MathuraMG** [comment]
@spiray is taking a look

**Comment by spiray** [comment]
@MathuraMG I assume we want to do `Math.round()` vs. `Math.floor()`, `Math.ceil()`, or `Math.trunc()`, right?

**Comment by MathuraMG** [comment]
yes yes! sorry for the delay!

**Comment by spiray** [comment]
@MathuraMG This issue can be closed. It was fixed in #108.

**Comment by MathuraMG** [comment]
oh yes! @spiray - just a quick note. Next time we make a PR, we can add Fixes <issue number> to it. It automatically closes the issue :)
