### ISSUE TITLE
change canvas default value

### ISSUE THREAD

**Issue by MathuraMG** [processing/p5.accessibility#63]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 
If the createCanvas function is not called, the default is 100, 100. Right now the default value is 0,0
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by lm-n** [comment]
Is this in the web editor?

**Comment by MathuraMG** [comment]
Actually.. I take this back. I tested this today, shall I close it? @lm-n 
[Test link here](http://alpha.editor.p5js.org/mathura/sketches/S13lr65eQ)
