### ISSUE TITLE
Spaces in color

### ISSUE THREAD

**Issue by lm-n** [processing/p5.accessibility#77]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Feature enhancement details:
Improve readability by adding spaces in outputs. I suggest adding a space between color names and RGB values. Currently colors in outputs read: 
"red(255,0,0) rect" for shapes 
"Dogs - 260(red(255, 0, 0))" for text
I suggest they read: 
"red (255,0,0) rect" for shapes 
"Dogs - 260 (red (255, 0, 0))" for text

**Comment by git-ebetts** [comment]
@lm-n @MathuraMG @mithru 
It hasn't been officially assigned but I've been working on this issue.

**Comment by MathuraMG** [comment]
@git-ebetts
