### ISSUE TITLE
Table output does not display shapes with values 0 in x or y pos 

### ISSUE THREAD

**Issue by lm-n** [processing/p5.accessibility#80]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 
Here the rect is not displayed in table output:
function setup() {
  createCanvas(300, 300);
}

function draw(){
  background(25);
  fill(255,0,0);
  ellipse(100,100,20,20);
  rect(200, 0, 26, 50);
}

while here it is: 
function setup() {
  createCanvas(300, 300);
}

function draw(){
  background(25);
  fill(255,0,0);
  ellipse(100,100,20,20);
  rect(200, 100, 26, 50);
}

if the values are <= 20 for x and y pos the shape doesn't show up 😢

**Comment by jbrundage** [comment]
@MathuraMG @lm-n my PR fixes this issue, it was just two operators to blame... would you prefer I ask before fixing an issue assigned to someone else? (I naturally would have if it involved more than a few lines of code)

**Comment by lm-n** [comment]
@jbrundage thanks for your PR! @mithru @MathuraMG and I will take a look as soon we get chance. Some of us where/are traveling but we'll get back to u ASAP! If you are interested in an issue just comment on it and if it is not assigned to anyone we will assign it to you. Commenting on the issues helps so that our contributors can focus on issues that no one else is working on. Thanks again :D
